// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountingController from "./accounting_controller"
application.register("accounting", AccountingController)

import CopyClipboardController from "./copy_clipboard_controller"
application.register("copy-clipboard", CopyClipboardController)

import CustomerSearchController from "./customer_search_controller"
application.register("customer-search", CustomerSearchController)

import HolidayToggleController from "./holiday_toggle_controller"
application.register("holiday-toggle", HolidayToggleController)

import QrCodeController from "./qr_code_controller"
application.register("qr-code", QrCodeController)

import SalesDatePickerController from "./sales_date_picker_controller"
application.register("sales-date-picker", SalesDatePickerController)

import ScheduleDatePickerController from "./schedule_date_picker_controller"
application.register("schedule-date-picker", ScheduleDatePickerController)

import ShiftConfirmationController from "./shift_confirmation_controller"
application.register("shift-confirmation", ShiftConfirmationController)

import TimeOptionsController from "./time_options_controller"
application.register("time-options", TimeOptionsController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ToastManagerController from "./toast_manager_controller"
application.register("toast-manager", ToastManagerController)
