import { application } from "../controllers/application";
import HolidayToggleController from "./holiday_toggle_controller.js";
import TimeOptionsController from "./time_options_controller";
import CopyClipboardController from "./copy_clipboard_controller.js";
import ScheduleDatePickerController from "./schedule_date_picker_controller.js";
import AccountingController from "./accounting_controller.js";
import CustomerSearchController from "./customer_search_controller.js";
import ToastController from "./toast_controller.js";
import ToastManagerController from "./toast_manager_controller.js";
import ShiftConfirmationController from "./shift_confirmation_controller.js";

application.register("holiday-toggle", HolidayToggleController);
application.register("time-options", TimeOptionsController);
application.register("copy-clipboard", CopyClipboardController);
application.register("schedule-date-picker", ScheduleDatePickerController);
application.register("accounting", AccountingController);
application.register("customer-search", CustomerSearchController);
application.register("toast", ToastController);
application.register("toast-manager", ToastManagerController);
application.register("shift-confirmation", ShiftConfirmationController);
