require:
  - rubocop-rails
  - rubocop-fjord
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - app/views/**/*
    - config/**/*
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
    - app/controllers/stylists/shift_settings_controller.rb
    - app/controllers/stylists/shift_settings/working_hours_controller.rb
    - app/controllers/customers/reservations_controller.rb
    - app/controllers/customers/stylists/weeklies_controller.rb
    - app/controllers/stylists/schedules_controller.rb
    - app/controllers/stylists/reservations_controller.rb
    - app/models/reservation.rb
    - app/models/menu.rb
    - app/models/schedule.rb
    - db/seeds/shift_settings_date_based.rb
    - spec/system/stylists/shift_settings/working_hours_spec.rb
    - spec/system/stylists/shift_settings/holidays_spec.rb
    - spec/system/stylists/shift_settings/shift_settings_spec.rb
    - spec/system/stylists/schedules_spec.rb
    - spec/system/stylists/reservations_spec.rb
    - spec/system/customers/reservations_history_spec.rb
    - spec/models/schedule_spec.rb
    - spec/system/stylists/shift_settings/defaults_spec.rb
    - spec/system/stylists/dashboards_spec.rb

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "app/models/user.rb"
    - "app/controllers/stylists/shift_settings/holidays_controller.rb"
Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "config/environments/development.rb"
    - "config/routes.rb"

Style/MultilineIfModifier:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
  IndentationWidth: 2
