require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-fjord
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - app/views/**/*
    - config/**/*
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
  Exclude:

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Exclude:

RSpec/NestedGroups:
  Exclude:

RSpec/LetSetup:
  Exclude:

Metrics/ClassLength:
  Exclude:
    - app/models/accounting.rb

Metrics/CyclomaticComplexity:
  Exclude:

Metrics/PerceivedComplexity:
  Exclude:

Metrics/AbcSize:
  Max: 20
  Exclude:
    - app/controllers/stylists/accountings_controller.rb

Metrics/MethodLength:
  Max: 20
  Exclude:

Metrics/BlockLength:
  Exclude:
    - spec/requests/**/*

RSpec/NoExpectationExample:
  Exclude:

Style/MultilineIfModifier:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
  IndentationWidth: 2
