require:
  - rubocop-rails
  - rubocop-fjord
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - app/views/**/*
    - config/**/*
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "app/models/user.rb"
Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "config/environments/development.rb"
    - "config/routes.rb"
