require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-fjord
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - app/views/**/*
    - config/**/*
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Metrics/ParameterLists:
  Max: 6
  Exclude:
    - spec/system/stylists/sales_spec.rb

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/system/stylists/sales_spec.rb

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
  Exclude:

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/system/stylists/sales_spec.rb
    - spec/mailers/reservation_mailer_spec.rb

RSpec/NestedGroups:
  Exclude:

RSpec/LetSetup:
  Exclude:

Metrics/ClassLength:
  Exclude:
    - app/models/accounting.rb
    - app/mailers/reservation_mailer.rb
    - app/controllers/customers/reservations_controller.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/stylists/sales_controller.rb

Metrics/PerceivedComplexity:
  Exclude:

Metrics/AbcSize:
  Max: 20
  Exclude:
    - app/controllers/stylists/accountings_controller.rb
    - app/controllers/stylists/sales_controller.rb
    - spec/system/stylists/sales_spec.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/system/stylists/sales_spec.rb

Metrics/BlockLength:
  Exclude:
    - spec/requests/**/*
    - lib/tasks/**/*.rake

RSpec/NoExpectationExample:
  Exclude:

RSpec/AnyInstance:
  Exclude:
    - spec/mailers/reservation_mailer_spec.rb

RSpec/StubbedMock:
  Exclude:
    - spec/mailers/reservation_mailer_spec.rb

Style/MultilineIfModifier:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
  IndentationWidth: 2
